### ISSUE TITLE
Allow custom_card to auto detect local path

### ISSUE THREAD

**Issue by ciotlosm** [custom-components/custom_cards#7]
We should allow custom paths for cards:
Examples:
```
/local/beer-card.js?v=0.0.1
/local/custom-lovelace/gauge-card/gauge-card.js
/local/custom-ui/gauge-card.js
```

The card should make up the path to cards in www based on resources entries and work accordingly.

**Comment by ludeeus** [comment]
Corrected in this code:
There is also an issue @ https://github.com/ciotlosm/custom-lovelace/issues/84 for this

<https://github.com/custom-components/custom_cards/tree/autodetect_location>
Needs some testing before merge.
